# Generated by Django 4.1.7 on 2023-02-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='concluida_em',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
